const data=[
{id:"2607161237501818539957",customer:"Sprint.Gio",item:"Motor & Parts",total:"Rp 12.500.000",status:"Selesai",date:"16 Jul 2026"},
{id:"2607150912450001123456",customer:"Gio Garage",item:"Custom Body",total:"Rp 4.750.000",status:"Diproses",date:"15 Jul 2026"},
{id:"2607121800117788990011",customer:"SMR GARAGE77",item:"Service & Setup",total:"Rp 2.850.000",status:"Selesai",date:"12 Jul 2026"},
{id:"2607100833445566778899",customer:"Archila Garage",item:"Exhaust Custom",total:"Rp 1.950.000",status:"Menunggu",date:"10 Jul 2026"}];

const nav=[["⌂","Dashboard","#/"],["▣","Collection Order","#/orders"],["♙","Customer","#/customers"],["▤","Laporan","#/reports"]];
function shell(body,active,title){return `<div class="layout"><aside class="side"><div class="logo"><i>G</i><div>Sprint.<span>Gio</span></div></div><div class="section">MENU UTAMA</div><nav class="nav">${nav.map((n,i)=>`<a class="${active===i?"active":""}" href="${n[2]}"><strong>${n[0]}</strong>${n[1]}</a>`).join("")}</nav><div class="bottom">Panel Administrasi<br><b>Sprint.Gio</b></div></aside><main class="main"><header class="top"><div class="crumb">${title}</div><div class="profile"><span>Admin</span><div class="avatar">A</div></div></header><section class="content">${body}</section></main></div>`}
function rows(list){return `<table><thead><tr><th>ID ORDER</th><th>CUSTOMER</th><th>ITEM</th><th>TOTAL</th><th>STATUS</th><th>TANGGAL</th></tr></thead><tbody>${list.map(o=>`<tr class="click" onclick="location.hash='/orders/${o.id}'"><td><b>${o.id}</b></td><td>${o.customer}</td><td>${o.item}</td><td>${o.total}</td><td><span class="status ${o.status==="Selesai"?"done":"process"}">${o.status}</span></td><td>${o.date}</td></tr>`).join("")}</tbody></table>`}
function dashboard(){return shell(`<div class="welcome"><div><h1>Dashboard</h1><div class="muted">Ringkasan aktivitas Sprint.Gio hari ini.</div></div><a class="btn" href="#/orders">+ Buat Order</a></div><div class="cards"><div class="card"><div class="cardtop"><span class="muted">Total Order</span><div class="icon">↗</div></div><div class="num">128</div><div class="trend">+12% bulan ini</div></div><div class="card"><div class="cardtop"><span class="muted">Selesai</span><div class="icon">✓</div></div><div class="num">96</div><div class="trend">+8 order minggu ini</div></div><div class="card"><div class="cardtop"><span class="muted">Diproses</span><div class="icon">◷</div></div><div class="num">24</div><div class="trend">Sedang berjalan</div></div><div class="card"><div class="cardtop"><span class="muted">Menunggu</span><div class="icon">!</div></div><div class="num">8</div><div class="trend">Perlu perhatian</div></div></div><div class="grid"><div class="panel"><div class="head"><h2>Order Terbaru</h2><a class="btn light" href="#/orders">Lihat Semua</a></div>${rows(data.slice(0,3))}</div><div class="panel"><div class="head"><h2>Aktivitas</h2></div><div class="activity"><div class="act"><i class="dot"></i><div><b>Order selesai</b><p>Sprint.Gio — Motor & Parts</p></div></div><div class="act"><i class="dot"></i><div><b>Order baru</b><p>Gio Garage — Custom Body</p></div></div><div class="act"><i class="dot"></i><div><b>Update service</b><p>SMR GARAGE77 — Setup</p></div></div></div></div></div>` ,0,"Dashboard")}
function orders(){return shell(`<div class="welcome"><div><h1>Collection Order</h1><div class="muted">Kelola seluruh data order Sprint.Gio.</div></div><button class="btn" onclick="alert('Form order bisa ditambahkan di sini')">+ Tambah Order</button></div><div class="panel"><div class="head"><h2>Semua Order</h2><button class="btn light" onclick="alert('Filter siap dikembangkan')">Filter</button></div>${rows(data)}</div>`,1,"Collection Order")}
function detail(id){let o=data.find(x=>x.id===id);return shell(o?`<div class="breadcrumb">Collection Order / Detail</div><div class="welcome"><div><h1>Detail Order</h1><div class="muted">${o.id}</div></div><a class="btn light" href="#/orders">← Kembali</a></div><div class="detail"><div class="panel"><div class="head"><h2>Informasi Order</h2><span class="status ${o.status==="Selesai"?"done":"process"}">${o.status}</span></div><div class="info">${[["ID Order",o.id],["Customer",o.customer],["Item",o.item],["Total",o.total],["Tanggal",o.date]].map(x=>`<div class="row"><span>${x[0]}</span><b>${x[1]}</b></div>`).join("")}</div></div><div class="panel"><div class="head"><h2>Aksi</h2></div><div class="info"><button class="btn" style="width:100%;margin-bottom:10px" onclick="alert('Status diperbarui')">Ubah Status</button><button class="btn light" style="width:100%" onclick="print()">Cetak Detail</button></div></div></div>`:`<div class="empty">Order tidak ditemukan<br><br><a class="btn" href="#/orders">Kembali</a></div>`,1,"Detail Order")}
function simple(title,desc,key){return shell(`<div class="welcome"><div><h1>${title}</h1><div class="muted">${desc}</div></div></div><div class="panel"><div class="empty">Halaman ${title} siap dikembangkan.</div></div>`,key,title)}
function render(){let p=location.hash.replace("#","")||"/";document.getElementById("app").innerHTML=p==="/" ? dashboard():p==="/orders"?orders():p.startsWith("/orders/")?detail(p.split("/")[2]):p==="/customers"?simple("Customer","Kelola data customer.",2):p==="/reports"?simple("Laporan","Lihat ringkasan laporan.",3):dashboard()}
addEventListener("hashchange",render);render();